#!/usr/bin/env lua































local ok_sh, shield = pcall(require, "fastfi.db.shield")
local ok_sv, subvendo = pcall(require, "fastfi.db.subvendo")
local file_util = require("fastfi.util.file")

local function sh(cmd)
    local f = io.popen(cmd .. " 2>/dev/null")
    if not f then return "" end
    local s = f:read("*a") or ""
    f:close()
    return s
end
local function trim(s) return (s or ""):gsub("^%s+", ""):gsub("%s+$", "") end
local function uci_get(k) return trim(sh("uci -q get " .. k)) end
local function is_vlan(v) v = tonumber(v); return v and v >= 1 and v <= 4094 end






local function derive_cidr(gw, subnet)
    subnet = trim(subnet or "")
    if subnet:match("^%d+%.%d+%.%d+%.%d+/%d+$") then return subnet end
    gw = trim(gw or "")
    local a, b, c = gw:match("^(%d+)%.(%d+)%.(%d+)%.")
    if a then return string.format("%s.%s.%s.0/24", a, b, c) end
    return nil
end

local function lan_cidrs()
    local cidrs = { "10.0.0.0/24" }
    local seen = { ["10.0.0.0/24"] = true }
    if ok_sv and subvendo then
        for _, sv in ipairs(subvendo.list_enabled()) do
            if sv.is_default ~= 1 and is_vlan(sv.vlan_id) then
                local cidr = derive_cidr(sv.gateway, sv.subnet)
                if cidr and not seen[cidr] then
                    seen[cidr] = true
                    table.insert(cidrs, cidr)
                end
            end
        end
    end
    return cidrs
end




local DOH_FALLBACK_IPS = {
    ["dns.google"]               = { "8.8.8.8", "8.8.4.4" },
    ["cloudflare-dns.com"]         = { "1.1.1.1", "1.0.0.1" },
    ["mozilla.cloudflare-dns.com"] = { "1.1.1.1", "1.0.0.1" },
}

local function resolve_ips(domain)
    local ips = {}
    for _, fb in ipairs(DOH_FALLBACK_IPS[domain] or {}) do table.insert(ips, fb) end
    
    
    local out = sh(string.format("nslookup %s 1.1.1.1", domain))
    for ip in out:gmatch("Address 1:%s*([%d%.]+)") do table.insert(ips, ip) end
    for ip in out:gmatch("^Address:%s*([%d%.]+)") do table.insert(ips, ip) end
    
    local seen, out_ips = {}, {}
    for _, ip in ipairs(ips) do
        if ip:match("^%d+%.%d+%.%d+%.%d+$") and not seen[ip] then
            seen[ip] = true
            table.insert(out_ips, ip)
        end
    end
    return out_ips
end





local function snapshot_set(setname)
    local out = sh("nft list set inet fastfi_shield " .. setname)
    if out == "" then return nil end
    local elems = out:match("elements%s*=%s*{%s*(.-)%s*}")
    return elems 
end


if not ok_sh or not shield then
    os.execute("logger -t fastfi-shield 'shield db module unavailable; aborting'")
    return
end

shield.self_seed()

local cfg = shield.read_config()
local manual    = shield.read_list("blocked_domains")
local allowed   = shield.read_list("allowed_domains")
local starlink  = shield.read_list("starlink_domains")
local doh_list = shield.get_doh_domains()

local starlink_on = cfg.starlink_enabled   == 1
local force_dns   = cfg.force_dns_enabled  == 1
local doh_on      = cfg.doh_block_enabled   == 1
local quic_on     = cfg.quic_block_enabled == 1




local blocked = {}
local function add_block(d)
    if shield.is_overridden(d, allowed) then return end 
    for _, x in ipairs(blocked) do if x == d then return end end
    table.insert(blocked, d)
end
if starlink_on then for _, d in ipairs(starlink) do add_block(d) end end
if doh_on then for _, d in ipairs(doh_list) do add_block(d) end end
for _, d in ipairs(manual) do add_block(d) end



local override_lines = shield.overrides_needed(allowed, blocked)


local conf_lines = { "# FastFi Shield - generated by fastfi-shield.lua, do not edit." }
for _, d in ipairs(blocked) do
    table.insert(conf_lines, string.format("address=/%s/0.0.0.0", d))
end
for _, a in ipairs(override_lines) do
    table.insert(conf_lines, string.format("server=/%s/#", a))
end

local conf_path = "/etc/dnsmasq.d/fastfi-block.conf"
local active = (#blocked > 0) or force_dns or quic_on or starlink_on or doh_on
if #conf_lines > 1 then
    os.execute("mkdir -p /etc/dnsmasq.d 2>/dev/null")
    file_util.write(conf_path, table.concat(conf_lines, "\n") .. "\n")
else

    os.remove(conf_path)
end












os.execute("/etc/init.d/dnsmasq restart 2>/dev/null")


local cidrs = lan_cidrs()


local starlink_elems = snapshot_set("fastfi_starlink_ips")
local doh_ips = {}
if doh_on then
    for _, d in ipairs(doh_list) do
        for _, ip in ipairs(resolve_ips(d)) do table.insert(doh_ips, ip) end
    end
end
local doh_elems = (#doh_ips > 0) and table.concat(doh_ips, ", ") or nil

if not active then
    
    
    os.execute("nft delete table inet fastfi_shield 2>/dev/null")
    file_util.write("/etc/fastfi/security/.last_apply", os.time() .. "\n")
    os.execute("logger -t fastfi-shield 'Shield inactive; dnsmasq conf cleared, nft table removed'")
    return
end

local L = {}
local function emit(s) table.insert(L, s) end

emit("table inet fastfi_shield {")





if starlink_on then
    local elems = (starlink_elems and starlink_elems ~= "") and
        (" elements = { " .. starlink_elems .. " }") or ""
    emit(string.format("    set fastfi_starlink_ips { type ipv4_addr; flags interval;%s }", elems))
end


if doh_on then
    local elems = doh_elems and (" elements = { " .. doh_elems .. " }") or ""
    emit(string.format("    set fastfi_doh_ips { type ipv4_addr; flags interval;%s }", elems))
end


if force_dns then
    emit("    chain force_dns {")
    emit("        type nat hook prerouting priority dstnat; policy accept;")
    for _, c in ipairs(cidrs) do
        emit(string.format("        ip saddr %s udp dport 53 redirect to 53", c))
        emit(string.format("        ip saddr %s tcp dport 53 redirect to 53", c))
    end
    emit("    }")
end


if #blocked > 0 or quic_on then
    emit("    chain block {")
    emit("        type filter hook forward priority mangle; policy accept;")
    if starlink_on then
        emit("        ip daddr @fastfi_starlink_ips drop")
    end
    if doh_on then
        emit("        ip daddr @fastfi_doh_ips drop")
    end
    if quic_on then
        for _, c in ipairs(cidrs) do
            emit(string.format("        ip saddr %s udp dport 443 drop", c))
        end
    end
    emit("    }")
end

emit("}")
local block = table.concat(L, "\n")






local table_exists = sh("nft list table inet fastfi_shield") ~= ""
local script = (table_exists and "flush table inet fastfi_shield\n" or "") .. block

local tmp = "/tmp/fastfi-shield.nft"
file_util.write(tmp, script)
os.execute("nft -f " .. tmp .. " >/dev/null 2>&1")
os.execute("rm -f " .. tmp .. " 2>/dev/null")

file_util.write("/etc/fastfi/security/.last_apply", os.time() .. "\n")
os.execute(string.format(
    "logger -t fastfi-shield 'Shield applied: %d domain(s) blocked, %d override(s), force_dns=%s quic=%s starlink=%s doh=%s'",
    #blocked, #override_lines, tostring(force_dns), tostring(quic_on),
    tostring(starlink_on), tostring(doh_on)))